// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6lBeqbkZaRw2GqMpjDhiKzj0iL_WtKo',
    appId: '1:192507252597:android:ba7e96be9afe8fb414cd3c',
    messagingSenderId: '192507252597',
    projectId: 'newchatapp-841c1',
    databaseURL: 'https://newchatapp-841c1-default-rtdb.firebaseio.com',
    storageBucket: 'newchatapp-841c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjyOcqdmX0Atk15ssx7xeWofyZ0UaZkA',
    appId: '1:192507252597:ios:6ef3c2f700c394f514cd3c',
    messagingSenderId: '192507252597',
    projectId: 'newchatapp-841c1',
    databaseURL: 'https://newchatapp-841c1-default-rtdb.firebaseio.com',
    storageBucket: 'newchatapp-841c1.appspot.com',
    androidClientId: '192507252597-hrg7uet7g8vv36k3uc5m0venm3so2ff2.apps.googleusercontent.com',
    iosClientId: '192507252597-harconp6742b0ikbghpa6la0hufvu9rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
